services:
  master_postgres:
    image: postgres:15-alpine
    container_name: order-service-postgres
    environment:
      POSTGRES_DB: order_service_db
      POSTGRES_USER: daria
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U daria -d order_service_db || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30

  order-service:
    build: .
    container_name: order-service-app
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://master_postgres:5432/order_service_db
      SPRING_DATASOURCE_USERNAME: daria
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      master_postgres:
        condition: service_healthy

volumes:
  postgres_data: